kramdown:
  syntax_highlighter: rouge
  input: GFM
  smart_quotes: ["apos", "apos", "quot", "quot"]
plugins:
  - jemoji

github:
  repository_name: ca
  repository_url: https://github.com/doubleu-labs/ca
exclude:
- "CNAME"
- "LICENSE"
