# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
---
name: Pages
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: wranders/markdown-to-pages-action@v0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - run: cp *.{crl,crt} CNAME dist/
    - uses: actions/upload-pages-artifact@v2
      with:
        path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deplotment.outputs.page_url }}
    steps:
    - uses: actions/deploy-pages@v1
      id: deployment